name: CI

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24.2'
      - name: Install swag
        run: go install github.com/swaggo/swag/cmd/swag@latest
      - name: Generate Swagger docs
        run: swag init -g service.go -d cmd/service,internal/api,internal/handler
      - name: Run tests
        run: make test
